# Generated by Django 5.1.7 on 2025-03-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='ytrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
        migrations.DeleteModel(
            name='YtRecord',
        ),
    ]
